spring:
  application:
    name: order-service

app:
  env: local
  version: 0.0.1-SNAPSHOT

logging:
  level:
    root: INFO
    com.example.logging_demo: INFO

management:
  endpoints:
    web:
      exposure:
        include: loggers,env,health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      service: ${spring.application.name}
      env: ${app.env}
      version: ${app.version}
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: ${app.version}
    env: ${app.env}
    description: Logging demo application with structured logs and metrics